version: "3.2"
services:
  db:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes: 
      - ./db:/docker-entrypoint-initdb.d/:ro
    container_name: guidap_mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    depends_on:
      - db
    networks:
      - backend
    ports:
      - "3002:80"
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}
    volumes: 
      - /sessions
    container_name: guidap_phpmyadmin
  app:
    build: .
    image: docker.guidap_marketplace_api
    depends_on:
      - db
    command: sh -c "/wait && npm start" 
    stdin_open: true
    tty: true
    networks:
      - frontend
      - backend
    environment:
      - DB_USER=${MYSQL_USER}
      - DB_HOST=db
      - DB_PORT=${MYSQL_PORT}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_DATABASE=${MYSQL_DATABASE}
      - WAIT_HOSTS=${WAIT_HOSTS}
      - WAIT_HOSTS_TIMEOUT=60
    volumes:
      - ./app/:/app
      # - node_modules:/node_modules
    ports:
      - "3000:3000"
    restart: unless-stopped
    container_name: docker.guidap_app
volumes:
  node_modules:
networks:
  frontend:
  backend: