### TO SEND REQUEST YOU NEED INSTALL REST Client ###
### (Ctrl+P) ext install humao.rest-client ###


GET http://localhost:3000


### Check users routes 
GET http://localhost:3000/user HTTP/1.1

### 
POST http://localhost:3000/user/register



### CHECK API ROUTES
GET http://localhost:3000/api/leisurecentre HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MTQwMDM5OTB9.Ib7ubByEdSYlxwcEfE-xfHxxM8T-tFmNCv-4FjBGGwM

### 
POST http://localhost:3000/api/leisurecentre
content-Type: application/json

{
    "centreName" : "SESQUIERES 2",
    "description" : "À 15 min de la place du Capitole, la base de sports et de loisirs de Sesquières est un espace de 62 hectares entièrement",
    "website" : "TEST UPDATE QUERY",
    "addressName" : "avenu des chalets",
    "cite" : "Launaguet",
    "zipCode" : 31140,
    "country" : "France",
    "categories" : ["Paddle","footsalle"]
}


###
PUT http://localhost:3000/api/leisurecentre/39
content-Type: application/json

{
    "centreName" : "SESQUIERES",
    "description" : "À 15 min de la place du Capitole, la base de sports et de loisirs de Sesquières est un espace de 62 hectares entièrement",
    "website" : "lac-sesquieres.fr",
    "addressName":"Allée des Foulques",
    "zipCode":31200,
    "cite":"Toulouse"
}

### Delete leisurecentre and leisurecentre_categories
DELETE http://localhost:3000/api/leisurecentre/49
